### PR TITLE
Issue/162

### PR DESCRIPTION
**Pull request by fulmicoton**
Need to add doc and fix benchmark for skip stuff, as this introduces a regression.

Before

`test postings::tests::bench_skip_next_p01                  ... bench:      98,518 ns/iter (+/- 2,588)
test postings::tests::bench_skip_next_p1                   ... bench:     349,363 ns/iter (+/- 22,189)
test postings::tests::bench_skip_next_p10                  ... bench:     694,869 ns/iter (+/- 18,959)
test postings::tests::bench_skip_next_p90                  ... bench:     475,763 ns/iter (+/- 41,806)`

After 

`test postings::tests::bench_skip_next_p01                  ... bench:     118,199 ns/iter (+/- 21,571)
test postings::tests::bench_skip_next_p1                   ... bench:     583,155 ns/iter (+/- 71,572)
test postings::tests::bench_skip_next_p10                  ... bench:   1,745,838 ns/iter (+/- 314,828)
test postings::tests::bench_skip_next_p90                  ... bench:     825,213 ns/iter (+/- 139,262)`

### CODE REVIEW

**Comment by fulmicoton** [comment]
perf following @lnicola 's fix

`test postings::tests::bench_skip_next_p01                  ... bench:     118,797 ns/iter (+/- 68,724)
test postings::tests::bench_skip_next_p1                   ... bench:     522,549 ns/iter (+/- 911,815)
test postings::tests::bench_skip_next_p10                  ... bench:   1,092,403 ns/iter (+/- 296,544)
test postings::tests::bench_skip_next_p90                  ... bench:     788,155 ns/iter (+/- 140,590)`

**Comment by lnicola** [comment]
Now this is awkward. After my last commit, on my Linux box I get:

```
master:
test postings::tests::bench_segment_intersection           ... bench:   4,844,086 ns/iter (+/- 31,711)
test postings::tests::bench_segment_postings               ... bench:   1,507,667 ns/iter (+/- 16,947)
test postings::tests::bench_skip_next_p01                  ... bench:     271,185 ns/iter (+/- 2,414)
test postings::tests::bench_skip_next_p1                   ... bench:     978,780 ns/iter (+/- 9,455)
test postings::tests::bench_skip_next_p10                  ... bench:   2,453,666 ns/iter (+/- 30,459)
test postings::tests::bench_skip_next_p90                  ... bench:   2,456,934 ns/iter (+/- 43,290)

pr:
test postings::tests::bench_segment_intersection           ... bench:   4,288,185 ns/iter (+/- 77,691)
test postings::tests::bench_segment_postings               ... bench:     902,715 ns/iter (+/- 6,661)
test postings::tests::bench_skip_next_p01                  ... bench:     256,476 ns/iter (+/- 1,006)
test postings::tests::bench_skip_next_p1                   ... bench:     882,680 ns/iter (+/- 12,647)
test postings::tests::bench_skip_next_p10                  ... bench:   2,134,069 ns/iter (+/- 22,092)
test postings::tests::bench_skip_next_p90                  ... bench:   2,071,681 ns/iter (+/- 37,390)
```

But on my Windows laptop:

```
master msvc:
test postings::tests::bench_segment_intersection           ... bench:   1,517,966 ns/iter (+/- 37,037)
test postings::tests::bench_segment_postings               ... bench:     250,053 ns/iter (+/- 5,968)
test postings::tests::bench_skip_next_p01                  ... bench:     112,303 ns/iter (+/- 2,918)
test postings::tests::bench_skip_next_p1                   ... bench:     402,410 ns/iter (+/- 57,233)
test postings::tests::bench_skip_next_p10                  ... bench:     821,704 ns/iter (+/- 39,991)
test postings::tests::bench_skip_next_p90                  ... bench:     528,711 ns/iter (+/- 19,004)

pr msvc:
test postings::tests::bench_segment_intersection           ... bench:   1,658,933 ns/iter (+/- 49,125)
test postings::tests::bench_segment_postings               ... bench:     389,987 ns/iter (+/- 8,192)
test postings::tests::bench_skip_next_p01                  ... bench:     114,259 ns/iter (+/- 2,409)
test postings::tests::bench_skip_next_p1                   ... bench:     429,326 ns/iter (+/- 16,827)
test postings::tests::bench_skip_next_p10                  ... bench:     953,432 ns/iter (+/- 23,779)
test postings::tests::bench_skip_next_p90                  ... bench:     690,607 ns/iter (+/- 29,506)

master gnu:
test postings::tests::bench_segment_intersection           ... bench:   1,488,365 ns/iter (+/- 228,597)
test postings::tests::bench_segment_postings               ... bench:     249,303 ns/iter (+/- 8,818)
test postings::tests::bench_skip_next_p01                  ... bench:     108,938 ns/iter (+/- 2,931)
test postings::tests::bench_skip_next_p1                   ... bench:     390,350 ns/iter (+/- 14,941)
test postings::tests::bench_skip_next_p10                  ... bench:     793,550 ns/iter (+/- 24,735)
test postings::tests::bench_skip_next_p90                  ... bench:     493,254 ns/iter (+/- 21,681)

pr gnu:
test postings::tests::bench_segment_intersection           ... bench:   1,670,598 ns/iter (+/- 41,827)
test postings::tests::bench_segment_postings               ... bench:     394,027 ns/iter (+/- 18,265)
test postings::tests::bench_skip_next_p01                  ... bench:     113,414 ns/iter (+/- 3,294)
test postings::tests::bench_skip_next_p1                   ... bench:     423,577 ns/iter (+/- 15,346)
test postings::tests::bench_skip_next_p10                  ... bench:     954,158 ns/iter (+/- 20,699)
test postings::tests::bench_skip_next_p90                  ... bench:     698,276 ns/iter (+/- 14,448)
```

**Comment by lnicola** [comment]
Also, why are my Windows times worse than those reported in https://github.com/tantivy-search/tantivy/pull/153?

**Comment by fulmicoton** [comment]
After the last commit

`test postings::tests::bench_skip_next_p01                  ... bench:     114,654 ns/iter (+/- 27,259)
test postings::tests::bench_skip_next_p1                   ... bench:     471,854 ns/iter (+/- 85,904)
test postings::tests::bench_skip_next_p10                  ... bench:   1,114,490 ns/iter (+/- 494,509)
test postings::tests::bench_skip_next_p90                  ... bench:     702,411 ns/iter (+/- 184,332)`

**Comment by fulmicoton** [comment]
```
test postings::tests::bench_skip_next_p01                  ... bench:     108,684 ns/iter (+/- 16,101)
test postings::tests::bench_skip_next_p1                   ... bench:     443,134 ns/iter (+/- 59,802)
test postings::tests::bench_skip_next_p10                  ... bench:     973,382 ns/iter (+/- 145,465)
test postings::tests::bench_skip_next_p90                  ... bench:     575,853 ns/iter (+/- 100,085)
```

**Comment by lnicola** [comment]
```
test postings::tests::bench_segment_intersection           ... bench:   1,551,921 ns/iter (+/- 146,069)
test postings::tests::bench_segment_postings               ... bench:     220,643 ns/iter (+/- 24,668)
test postings::tests::bench_skip_next_p01                  ... bench:     106,301 ns/iter (+/- 4,230)
test postings::tests::bench_skip_next_p1                   ... bench:     402,466 ns/iter (+/- 34,051)
test postings::tests::bench_skip_next_p10                  ... bench:     840,000 ns/iter (+/- 77,473)
test postings::tests::bench_skip_next_p90                  ... bench:     467,733 ns/iter (+/- 61,548)
```

**Comment by lnicola** [comment]
```
windows msvc:
test postings::tests::bench_segment_intersection           ... bench:   1,447,625 ns/iter (+/- 122,742)
test postings::tests::bench_segment_postings               ... bench:     206,747 ns/iter (+/- 19,893)
test postings::tests::bench_skip_next_p01                  ... bench:      99,848 ns/iter (+/- 7,773)
test postings::tests::bench_skip_next_p1                   ... bench:     374,617 ns/iter (+/- 36,732)
test postings::tests::bench_skip_next_p10                  ... bench:     840,755 ns/iter (+/- 53,914)
test postings::tests::bench_skip_next_p90                  ... bench:     475,140 ns/iter (+/- 60,780)

linux:
test postings::tests::bench_segment_intersection           ... bench:   4,309,849 ns/iter (+/- 26,054)
test postings::tests::bench_segment_postings               ... bench:     900,914 ns/iter (+/- 7,823)
test postings::tests::bench_skip_next_p01                  ... bench:     248,440 ns/iter (+/- 3,216)
test postings::tests::bench_skip_next_p1                   ... bench:     854,712 ns/iter (+/- 16,456)
test postings::tests::bench_skip_next_p10                  ... bench:   2,119,584 ns/iter (+/- 20,426)
test postings::tests::bench_skip_next_p90                  ... bench:   2,108,696 ns/iter (+/- 45,366)
```

**Pull request merged**
