### PR TITLE
WIP: Issue/46 LogMergePolicy

### PR DESCRIPTION
**Pull request by currymj**
Implements a LogMergePolicy as mentioned in #46.

I would like to add some tests. However, I'm not totally clear on what might need to be tested. Thoughts?

### CODE REVIEW

**Comment by fulmicoton** [comment]
I put a bunch of comments.

About unit test, you could make calls with very specific values. (no segment, X segment on the same level, X segment on level 0, X segments on level 2, segments below the lowest level threshold)

**Comment by fulmicoton** [comment]
@currymj Sorry I am new to the code review functionality. I wrote those comments weeks ago and apparently did not finalize the review. Let me know if those make sense.

**Comment by currymj** [comment]
This is all helpful advice! I was just digging through the Lucene code to try to reverse engineer how/why they use the lowest level setting, but your explanation makes a lot of sense. I don't think I will find it too difficult to add this and to just copy the logic from Lucene for adding a level cutoff whenever the floor is reached, etc.

**Comment by fulmicoton** [comment]
Cool. I'll test that at home on indexing wikipedia. It will probably shave off a lot of time over the current merge policy. If I have time, I'll make a visualization of how it behaves.

**Comment by currymj** [comment]
Right now the values for min merge size and segment size are very small hardcoded constants. They should probably be configurable somewhere -- maybe a LogMergePolicy instance should contain these parameters?

**Pull request merged**
