### PR TITLE
switch to fx hashmap

### PR DESCRIPTION
**Pull request by PSeitz**

### CODE REVIEW

**Comment by adamreichold** [comment]
Isn't it possible that the aggregation keys are user-controlled (say if Tantivy is used to power a web service with a generic interface) and hence this would enable DoS attacks?

**Comment by PSeitz** [comment]
I think there are a ton of attack vectors to DoS a search engine, when you have control over the query

**Comment by adamreichold** [comment]
> I think there are a ton of attack vectors to DoS a search engine, when you have control over the query

Agreed. For me, it is enough to know that you are aware of this.

**Review by fulmicoton — APPROVED** [review]
Is it actually helpful?

**Pull request merged**
