### PR TITLE
fix typ in doc

### PR DESCRIPTION
**Pull request by kkanas**
Signed-off-by: Krzysztof Kanas <kkanas@fastmail.com>

### CODE REVIEW

**Comment by fulmicoton** [comment]
It is not a typo https://en.wikipedia.org/wiki/If_and_only_if

**Comment by kkanas** [comment]
Oh, didn't came across those type of notation very often in doc. Usually if works, ok. Thanks for clarification.

**Comment by fulmicoton** [comment]
iff means "if and only if".
We can think of expanding the abbrevation everywhere it if it is not common enough.

**Comment by fulmicoton** [comment]
Created issue #1236

**Pull request closed without merging**
