### PR TITLE
Issue/191

### PR DESCRIPTION
**Pull request by fulmicoton**

### CODE REVIEW

**Comment by fulmicoton** [comment]
(it is not ready yet...)

**Comment by cetra3** [comment]
What is the status of this PR?

**Comment by fulmicoton** [comment]
@cetra3 It is going to land eventually relatively. I stopped working on it as its build was broken due to https://github.com/rust-lang/rust/issues/42903. Do you have a specific need for it?

**Comment by cetra3** [comment]
No need at the moment. I was actually thinking of implementing stemming but stumbled upon this PR and was curious of the progress!

**Pull request merged**
