### PR TITLE
add FastFieldRangeQuery, rename

### PR DESCRIPTION
**Pull request by PSeitz**
add FastFieldRangeQuery
add reexport
rename module

preparation for support on string range queries in quickwit

### CODE REVIEW

**Review by trinity-1686a — APPROVED** [review]
`FastFieldRangeWeight`  implements `Query`, imo that should be removed if we now have a proper Query type for that

**Comment by PSeitz** [comment]
> `FastFieldRangeWeight`  implements `Query`, imo that should be removed if we now have a proper Query type for that

The RangeWeight is still a valid export, which can be used in a custom Query

**Comment by trinity-1686a** [comment]
i don't mean to remove `FastFieldRangeWeight`, but to remove `impl Query for FastFieldRangeWeight`

**Comment by PSeitz** [comment]
> i don't mean to remove `FastFieldRangeWeight`, but to remove `impl Query for FastFieldRangeWeight`

Ah yes that makes sense

**Pull request merged**
