### PR TITLE
Switch from error-chain to failure crate

### LINKED ISSUE #373: Ditch `error_chain` for failure?
Open question : Should we ditch `error_chain` for `failure`?

I cannot upgrade `error_chain`, because `Error` are not `Sync`  in later versions.

### PR DESCRIPTION
**Pull request by drusellers**
Closes #373 

[Failure](https://github.com/rust-lang-nursery/failure)

I implemented the custom fail type: https://boats.gitlab.io/failure/custom-fail.html

This was pretty easy and felt like it removed more code than it added.

### CODE REVIEW

**Comment by petr-tik** [comment]
hey, you must have seen it already, your appveyor config is older than master. You should merge master back into your PR branch and see if it passes the tests

Your appveyor file has 
```bash
cargo run --example simple_search
```
which fails with the message below

```bash
error: no example target named `simple_search`
```

because there is no more simple_search example

change to cargo build --examples like in [current master appveyor file](https://github.com/tantivy-search/tantivy/blob/master/appveyor.yml#L22)

**Comment by petr-tik** [comment]
have a look at my PR #380. Don't mean to take your work away from you, but it was easier to open a PR to upstream tantivy than to find your branch. Feel free to merge and close it yourself. 

I only wanted to do it, because I am doing #235 and wanted to base my PR off your work

**Comment by drusellers** [comment]
@petr-tik no worries at all, i'm sorry that I didn't see this sooner. i'll make sure this is squared away shortly.

**Comment by drusellers** [comment]
@petr-tik i rebased on master (thank you for the heads up) and it looks like all is well now. sorry for the hassle

**Comment by petr-tik** [comment]
@drusellers glad I helped 

@fulmicoton feel free to close #380, if/when you merge this

**Comment by fulmicoton** [comment]
Maybe we should add an alias from `tantivy::Error` to `tantivy::TantivyError` and mark it as deprecated to make it the transition smoother.

**Comment by fulmicoton** [comment]
thanks for all this work!

**Comment by fulmicoton** [comment]
Thanks for all this work @drusellers . We may want to revisit it some day to add backtrace in some strategic part, but it is probably too soon to tell whre it is needed. 

Merging!

**Pull request merged**
