### PR TITLE
RegexQuery performance: make it possible to cache Regexes

### PR DESCRIPTION
**Pull request by brainlock**
See https://github.com/tantivy-search/tantivy/issues/639

### CODE REVIEW

**Comment by fulmicoton** [comment]
Can you check if https://github.com/tantivy-search/tantivy/pull/641 works for you?

**Comment by brainlock** [comment]
Closed in favor of #641

**Comment by brainlock** [comment]
> Can you check if #641 works for you?

It does, thank you! :)

**Comment by fulmicoton** [comment]
Awesome thank you, and sorry for the confusing instructions!

**Pull request closed without merging**
