### PR TITLE
Support for indexed bytes fast field

### PR DESCRIPTION
**Pull request by raultang**
I am trying to implement string fast field, which equivalent to elasticsearch [keyword type](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html),
This is probably also relate to https://github.com/tantivy-search/tantivy/issues/832

Base on my current understanding, bytes fast filed is similar to int fast filed, so not much special need to handle.
This change only include `SingleValue` which meet my needs right now, `MultiValues` is more complicated and need more time.

### CODE REVIEW

**Comment by fulmicoton** [comment]
I am not sure this is the way elasticsearch. I am not sure, but aren't they encoding the term ordinal in the docvalue?

**Comment by raultang** [comment]
> I am not sure this is the way elasticsearch. I am not sure, but aren't they encoding the term ordinal in the docvalue?

My understanding it also store the term direct in column store, later on doing aggregation etc can avoid ordinal lookup costs.

Anyway, this pull request is more relate to make the bytes fast field indexed, then it is searchable, string is just an example.

**Comment by fulmicoton** [comment]
Sorry for the late answer, i'll start reviewing your code.

**Comment by fulmicoton** [comment]
The PR will require more work. I pulled it as a feature branch in tantivy and invited you as a developer so we can iterate on this.

**Comment by raultang** [comment]
Sure, that would be great.

**Comment by fulmicoton** [comment]
@raultang Have you seen my email?

**Comment by raultang** [comment]
@fulmicoton 
Sorry, just saw the email. And see detail in the email.

**Comment by fulmicoton** [comment]
This has been reworked in a different PR.

**Pull request closed without merging**
