### PR TITLE
[RFC] Python bindings

### PR DESCRIPTION
**Pull request by poljar**
This patch-set implements python bindings for Tantivy.

The bindings are written using [PyO3](https://github.com/PyO3/pyo3) and thus require rust nightly.

Some parts of the Tantivy API are omitted for now (like the SegmentReader) while some parts are made a little bit more pythonic using optional arguments instead of builder patterns.

The search method of the Searcher struct is incomplete and only allows a single TopCollector as its collector argument. Since the method is generic and python doesn't support generics, it has proven to be quite tricky to allow multiple differing collectors to be passed to the function in a dynamic way.

The first couple of patches add some functionality or expose some structs publicly in Tantivy that are required for the python bindings.

The last patch finally adds the python bindings as a sub-crate to Tantivy. To build the bindings a setup.py file is provided that requires [setuptools-rust](https://github.com/PyO3/setuptools-rust) or [pyo3-pack](https://github.com/PyO3/pyo3-pack) can be used. Both of the methods allow the bindings to be uploaded to pypi.

### CODE REVIEW

**Comment by petr-tik** [comment]
This is a great idea. I think it will help others use tantivy from their python projects - thanks for a great PR. 

According to the travis log, nix-0.11.0 fails to compile because of signed/unsigned 32-bit number confusion. 

https://travis-ci.org/tantivy-search/tantivy/jobs/540729621

Lurking around the [nix repo](https://github.com/nix-rust/nix/releases) I don't see any relevant issues. However, there have been new releases, including nix-0.14.0. 

Can you update Cargo.toml in top-level dir and try building again?

**Comment by poljar** [comment]
What would you like me to bump? 

Nix isn't a direct dependency of Tantivy, Nix is a dependency of atomicwrites. While there have been new Nix releases, there hasn't been a atomicwrites release that depends on a newer Nix version.

Am I missing something?

**Comment by fulmicoton** [comment]
@poljar This looks awesome.

I suggest we put that in its own repository : `tantivy-search/tantivy-py`.
Do not worry too much about nix. I don't think we care too much about python binding to compile on ARM for the moment.


> Some parts of the Tantivy API are omitted for now (like the SegmentReader) while some parts are made a little bit more pythonic using optional arguments instead of builder patterns.

That's perfectly fine. I only skimmed the code, but everything looks quite nice.
Actually, I think we should probably make that even more pythonic... We can discuss that later though.

The license looks like a MIT license.  If this is the case, could you mark it as such in the `Cargo.toml` manifest?

**Comment by poljar** [comment]
License is indeed MIT, added a commit that marks it in the Cargo.toml.

**Comment by fulmicoton** [comment]
@poljar are you ok with having this in a different repository?  If so can you send you PR to 
https://github.com/tantivy-search/tantivy-py ?

(You can ignore the `travis-ci` stuff.)

**Comment by poljar** [comment]
I don't mind at all. Just note that part of the patches are Tantivy changes. The python bindings will therefore depend on the git version of Tantivy.

Will prepare a PR soon.

**Comment by fulmicoton** [comment]
I think I am ok with the changes you made to tantivy. I can merge them
relatively rapidly.

**Comment by fulmicoton** [comment]
@poljar 

I am getting the following error

```
➜  python git:(matrix-org-python-bindings) ✗ python                 
Python 2.7.15+ (default, Oct  2 2018, 22:12:08) 
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tantivy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tantivy/__init__.py", line 1, in <module>
    from .tantivy import *
ImportError: tantivy/tantivy.so: undefined symbol: PyObject_GenericGetDict
>>> 
```

**Comment by poljar** [comment]
PyO3 does not support python2, are you getting the same error with python3? For reference https://github.com/PyO3/pyo3/pull/411.

**Comment by fulmicoton** [comment]
Thanks. Let's put that in the README!

**Comment by poljar** [comment]
Yeah, I completely forgot that python3 isn't the default python everywhere. I'll add a commit to the PR in the other repo.

**Comment by fulmicoton** [comment]
@poljar Hi. Any update on this work? @bloodbar started python bindings on its own and is offering to consolidate your work and his, and prepare the PR to tantivy-py.

**Comment by poljar** [comment]
What update was required? I opened the PR to tantivy-py and the README was updated to mention that python3 is required.

I did some more work to make it possible to use an arbitrary field for the top collector but was waiting for the initial PR to get the OK.

Is there something missing to get the initial PR merged?

**Comment by bloodbare** [comment]
@poljar You did a great job, I'm willing to have it for the guillotina.io project as object indexer, feel free to point out what is the status!

**Comment by poljar** [comment]
The bindings are perfectly usable, I use them in a project as well. The main thing that is missing is the ability to use differing collectors and maybe some other minor stuff i forgot about.

I'm quite happy how the python API turned out, sure it could be tweaked to be a l little bit more pythonic but it's decent to use already.

The [python tests](https://github.com/tantivy-search/tantivy-py/blob/5d9245260486bc1a43b1c0843a17b860e291d98d/tests/tantivy_test.py) that I wrote are a nice overview.

**Comment by fulmicoton** [comment]
@poljar I totally missed your PR ( O_O )
Apologies. Merging now, and @bloodbare and you can work off this.

**Comment by poljar** [comment]
Don't forget that the tantivy changes in this PR are needed for the bindings to compile, dunno if those got merged somewhere to tantivy.

Thanks for merging this.

**Comment by petr-tik** [comment]
Looks like we can close this PR, since we have merged the necessary changes to this repo and the rest is being done in tantivy-py

**Comment by fulmicoton** [comment]
Agreed.

**Pull request closed without merging**
