### PR TITLE
Fix typos and markdowns

### PR DESCRIPTION
**Pull request by kianmeng**
Found via these commands:

    codespell -L crate,ser,panting,beauti,hart,ue,atleast,childs,ond,pris,hel,mot
    markdownlint *.md doc/src/*.md --disable MD013 MD025 MD033 MD001 MD024 MD036 MD041 MD003

### CODE REVIEW

**Review by PSeitz — APPROVED** [review]
Nice, thanks!

**Comment by PSeitz** [comment]
can you run `cargo fmt`

**Comment by kianmeng** [comment]
> can you run `cargo fmt`

https://github.com/quickwit-oss/tantivy/pull/1445/commits/84295d5b35090fe74c16dbdef9ec93829e8696de

**Comment by PSeitz** [comment]
Ah sorry, you need to use nightly for formatting
`cargo +nightly fmt`

**Comment by guilload** [comment]
@kianmeng, if you fancy contributing to Quickwit, I'd happily review the same kind of PR in the [quickwit repo](https://github.com/quickwit-oss/quickwit) :)

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
